Project3_Loebe_Jamie: main.o Character.o Barbarian.o BlueMen.o HarryPotter.o Medusa.o Vampire.o
	g++ main.o Character.o Barbarian.o BlueMen.o HarryPotter.o Medusa.o Vampire.o -o Project3_Loebe_Jamie

main.o: main.cpp
	g++ -c main.cpp

Character.o: Character.cpp Character.hpp
	g++ -c Character.cpp

Barbarian.o: Barbarian.cpp Barbarian.hpp
	g++ -c Barbarian.cpp

BlueMen.o: BlueMen.cpp BlueMen.hpp
	g++ -c BlueMen.cpp

HarryPotter.o: HarryPotter.cpp HarryPotter.hpp
	g++ -c HarryPotter.cpp

Medusa.o: Medusa.cpp Medusa.hpp
	g++ -c Medusa.cpp

Vampire.o: Vampire.cpp Vampire.hpp
	g++ -c Vampire.cpp

clean:
	rm *.o
